name: ghar_sathi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  google_maps_flutter: ^2.5.3
  permission_handler: ^12.0.1
  baseflow_plugin_template: ^2.2.0

  cupertino_icons: ^1.0.8

  #for api call_log:
  http: ^1.6.0
  #esewa payment gateway
  esewa_flutter:

  #firebase core
  firebase_core:
  firebase_auth:


  #Image picker
  image_picker: ^1.2.1
  #for longitude_and_latitude_calculation
  geocoding: ^4.0.0

  get: ^4.7.2


  #JWT Token Handdle
  dio: ^5.9.0
  get_storage:





dev_dependencies:
  flutter_test:
    sdk: flutter

  google_fonts: ^6.3.2
  get: ^4.7.2
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1
  curved_navigation_bar: ^1.0.6
  flutter_launcher_icons: ^0.14.1



  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/blob.png
    - assets/images/homeGif.png
    - assets/images/GharSathiLogo.png
    - assets/images/on_boarding_images/
    - assets/logo/
    - assets/images/forgotPassword.png
    - assets/map_style.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/GharSathiLogo.png


